spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: z123456
    url: jdbc:mysql:///wx_shop?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null



server:
  context-path: /sell


